# Generated by Django 5.1.3 on 2025-05-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='journal_entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
